name: local-test
on:
 workflow_dispatch:
    inputs:
      job:
        description: 'feature branch'
        required: true
        default: 'feature-'
jobs:
  feature-deploy:
    runs-on: go-os
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull Config
        run: /bin/bash ./script/pull_config.sh dev
      - name: Build
        run: go build -o testCI ./main.go
      - name: Kill All
        run: /bin/bash ./script/kill.sh
      - name: Start All
        run: /bin/bash ./script/start.sh
      - name: Lookup
        run: ps -ef | grep testCI | grep -v grep